Repository scg-unibe-ch/ese2018-team7, pull requests merged in 2018-11, with the labels that each got.

#13 Implemented proper form validation
  frontend/src/app/app.module.ts
  frontend/src/app/jobEdit/jobEdit.component.html
  frontend/src/app/jobEdit/jobEdit.component.ts
  frontend/src/app/jobsEdit/jobsEdit.component.ts
  frontend/src/app/skillEdit/skillEdit.component.ts
Labels: help wanted

#17 Added Markdown
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.css
  frontend/src/app/app.module.ts
  frontend/src/app/jobEdit/jobEdit.component.css
  frontend/src/app/jobEdit/jobEdit.component.html
  frontend/src/app/jobEdit/jobEdit.component.ts
  frontend/src/app/jobViewDetails/jobViewDetails.component.html
Labels: enhancement

#22 Surprise dev
  backend/app/controllers/getLogo.ts
  backend/app/controllers/main.controller.ts
  backend/app/msApiKey.json
  backend/package-lock.json
  backend/package.json
  frontend/src/app/app.module.ts
  frontend/src/app/jobEdit/jobEdit.component.html
  frontend/src/app/registration/registration.component.css
  frontend/src/app/registration/registration.component.html
  frontend/src/app/registration/registration.component.ts
  frontend/src/app/selectLogo/selectLogo.component.css
  frontend/src/app/selectLogo/selectLogo.component.html
  frontend/src/app/selectLogo/selectLogo.component.spec.ts
  frontend/src/app/selectLogo/selectLogo.component.ts
Labels: enhancement

#24 Added Mail to User for contact
  backend/app/controllers/job/addJob.ts
  backend/app/controllers/user/register.ts
  backend/app/models/user.model.ts
  frontend/src/app/jobsEdit/jobsEdit.component.ts
  frontend/src/app/login/login.component.ts
  frontend/src/app/registration/registration.component.html
  frontend/src/app/registration/registration.component.ts
  frontend/src/app/user.ts
  frontend/src/app/usersEdit/usersEdit.component.css
  frontend/src/app/usersEdit/usersEdit.component.html
  frontend/src/app/usersEdit/usersEdit.component.ts
Labels: enhancement

#27 Hopefully fixes the registration bug
  backend/app/controllers/getLogo.ts
  backend/app/controllers/user/register.ts
  frontend/src/app/registration/registration.component.ts
Labels: bug

#29 Improved UI of registration form
  frontend/src/app/registration/registration.component.css
  frontend/src/app/registration/registration.component.html
  frontend/src/app/registration/registration.component.ts
Labels: enhancement

#28 Added Sorting function to usersEdit table
  frontend/src/app/usersEdit/usersEdit.component.css
  frontend/src/app/usersEdit/usersEdit.component.html
  frontend/src/app/usersEdit/usersEdit.component.ts
  frontend/src/app/usersEdit/usersEdit.dataProvider.ts
Labels: enhancement

#33 Moved Email from User to Company
  backend/app/controllers/job/addJob.ts
  backend/app/controllers/user/company/getCompany.ts
  backend/app/controllers/user/company/updateCompany.ts
  backend/app/controllers/user/login.ts
  backend/app/controllers/user/register.ts
  backend/app/enums/message.enum.ts
  backend/app/models/company.model.ts
  backend/app/models/user.model.ts
  frontend/src/app/accountSettings/accountSettings.component.css
  frontend/src/app/accountSettings/accountSettings.component.html
  frontend/src/app/accountSettings/accountSettings.component.ts
  frontend/src/app/company.ts
  frontend/src/app/jobsEdit/jobsEdit.component.ts
  frontend/src/app/jobsView/jobsView.component.ts
  frontend/src/app/login/login.component.ts
  frontend/src/app/message.ts
  frontend/src/app/registration/registration.component.html
  frontend/src/app/registration/registration.component.ts
  frontend/src/app/user.ts
  frontend/src/app/usersEdit/usersEdit.component.html
  frontend/src/app/usersEdit/usersEdit.component.ts
Labels: bug, enhancement
